services:
  todosDB:
    image: postgres:15.3
    container_name: todos-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todos
    volumes:
      - ./postgres:/var/lib/postgresql/data
